#!/bin/zsh -e
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
ENDCOLOR="\e[0m"

group_prefix=""
config_dir=""
dry_run=false

while (( "$#" )); do
  case "$1" in
    --group-prefix)
      group_prefix="$2"
      shift 2
      ;;
    --config-dir)
      config_dir="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=true
      shift
      ;;
    *)
      if [ -z "$config_dir" ]; then
        config_dir="conf/$1/sso_groups"
      else
        echo -e "${RED}ERROR: --config-dir and positional argument cannot be used together${ENDCOLOR}"
        exit 1
      fi
      shift
      ;;
  esac
done

if [ -z "$config_dir" ] ; then
    echo -e "${RED}ERROR: Please specify a subdirectory or use --config-dir${ENDCOLOR}"
    exit 1
fi

if ! [ -d $config_dir ] ; then
    echo -e "${RED}ERROR: The directory $config_dir doesn't exist${ENDCOLOR}"
    exit 1
fi

instance_arn=$(aws sso-admin list-instances --query 'Instances[0].InstanceArn' --output text --no-paginate)
identity_store_id=$(aws sso-admin list-instances --query 'Instances[0].IdentityStoreId' --output text --no-paginate)

echo
if [[ $instance_arn =~ ^arn:aws:sso:::instance/ssoins- && $identity_store_id =~ ^d-[a-zA-Z0-9]+$ ]]; then
  echo "${GREEN}Using default AWS SSO identity provider${ENDCOLOR}"
else
  echo "${GREEN}Using external identity provider${ENDCOLOR}"
fi
echo "    ${GREEN}SSO Instance ARN:      ${YELLOW}$instance_arn${ENDCOLOR}"
echo "    ${GREEN}SSO Identity Store ID: ${YELLOW}$identity_store_id${ENDCOLOR}"


get_group_id() {
    local group_id=$(aws identitystore list-groups --identity-store-id $identity_store_id \
                --filters "[{\"AttributePath\": \"DisplayName\", \"AttributeValue\": \"$1\"}]" \
                --query 'Groups[0].GroupId' --output text --no-paginate)
    echo $group_id
}


create_sso_group() {
  local sso_group_name=$group_prefix$1
  local description=$2
  local group_id=$(get_group_id $sso_group_name)

  if [[ "$group_id" != "None" ]]; then
    echo "${RED}Group ${YELLOW}$sso_group_name${RED} already exists.${ENDCOLOR}" 
    return 0
  fi

  if $dry_run; then
    echo "${GREEN}Would create group ${YELLOW}$sso_group_name${GREEN}...${ENDCOLOR}"
  else
    echo "${GREEN}Creating group ${YELLOW}$sso_group_name${GREEN}...${ENDCOLOR}"
    group_id=$(aws identitystore create-group \
      --identity-store-id $identity_store_id \
      --display-name $sso_group_name \
      --description "$description" \
      --query 'GroupId' \
      --output text --no-paginate
    )

    if [ -z "$group_id" ]; then
      echo "${RED}Error creating group ${YELLOW}$sso_group_name${ENDCOLOR}" >&2
      return 1
    fi

    echo "${GREEN}Group ${YELLOW}$sso_group_name${GREEN} created with ID ${YELLOW}$group_id${ENDCOLOR}"
  fi
  return 0
}


for FILE in ${config_dir}/*.yaml
do
  echo
  echo -e "${GREEN}====================================================================================================${ENDCOLOR}"
  echo -e "${YELLOW}    $FILE:${ENDCOLOR}"
  echo -e "${GREEN}----------------------------------------------------------------------------------------------------${ENDCOLOR}"
  echo
  
  json=$(cat $FILE | yq .)
  sso_group_name=$(echo $json | jq -r .sso_group_name)
  sso_group_name=$group_prefix$sso_group_name
  description=$(echo $json | jq -r .description)
  
  group_id=$(get_group_id $sso_group_name)

  if [[ "$group_id" == "None" ]]; then
    create_sso_group "$sso_group_name" "$description"
    if [ $? -ne 0 ]; then
      echo "${RED}Error creating group $sso_group_name${ENDCOLOR}"
    fi
  else 
    echo -e ${GREEN}The SSO group ${YELLOW}$sso_group_name${GREEN} exists.${ENDCOLOR}
  fi
done
echo

